// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt4wLz4PVDvXoZi3p7S9_TsxOUSBfK1zI',
    appId: '1:878272277745:web:c6119c19073ea6ae350d50',
    messagingSenderId: '878272277745',
    projectId: 'fir-project1-1f8f5',
    authDomain: 'fir-project1-1f8f5.firebaseapp.com',
    storageBucket: 'fir-project1-1f8f5.appspot.com',
    measurementId: 'G-Q8QR60V0ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc0d9xMOF12ZlI-azFgFqQYbSiFC80lVg',
    appId: '1:878272277745:android:e8a970697abffc47350d50',
    messagingSenderId: '878272277745',
    projectId: 'fir-project1-1f8f5',
    storageBucket: 'fir-project1-1f8f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcEsGHLzOSq_dpqdA9-vMwDiAHviEbf_U',
    appId: '1:878272277745:ios:1137813b916411bb350d50',
    messagingSenderId: '878272277745',
    projectId: 'fir-project1-1f8f5',
    storageBucket: 'fir-project1-1f8f5.appspot.com',
    iosBundleId: 'com.example.medicalStoreMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcEsGHLzOSq_dpqdA9-vMwDiAHviEbf_U',
    appId: '1:878272277745:ios:1137813b916411bb350d50',
    messagingSenderId: '878272277745',
    projectId: 'fir-project1-1f8f5',
    storageBucket: 'fir-project1-1f8f5.appspot.com',
    iosBundleId: 'com.example.medicalStoreMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt4wLz4PVDvXoZi3p7S9_TsxOUSBfK1zI',
    appId: '1:878272277745:web:497a1720ecd127ae350d50',
    messagingSenderId: '878272277745',
    projectId: 'fir-project1-1f8f5',
    authDomain: 'fir-project1-1f8f5.firebaseapp.com',
    storageBucket: 'fir-project1-1f8f5.appspot.com',
    measurementId: 'G-9QYJ1XQFP6',
  );
}
